USE master;  
GO 
 
IF DB_ID (N'RedBook') IS NULL
  RETURN;
ALTER DATABASE RedBook
SET SINGLE_USER --or RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO

IF DB_ID (N'RedBook') IS NULL
  RETURN;
DROP DATABASE RedBook;
GO