USE master;  
GO 
 
IF DB_ID (N'Test') IS NULL
  RETURN;
ALTER DATABASE Test
SET SINGLE_USER --or RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO

IF DB_ID (N'Test') IS NULL
  RETURN;
DROP DATABASE Test;
GO