USE ToolsStore;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'U' AND name = 'RS_ORDER_CONTENT')
BEGIN
  SELECT 1 AS VAR1
END

IF (OBJECT_ID('dbo.RS_ORDER_CONTENT') IS NOT NULL)
BEGIN 
  SELECT 2 AS VAR2
END

IF EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID('dbo.RS_ORDER_CONTENT') AND type = N'U')
BEGIN
  SELECT 3 AS VAR3
END