USE RedBook
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.CT_Squads(
	SquadId BIGINT IDENTITY(1,1) NOT NULL,
	SquadCode NVARCHAR(100) NOT NULL,
	SquadName NVARCHAR(100) NOT NULL,
 CONSTRAINT [PK_CT_Squads] PRIMARY KEY CLUSTERED 
(
	SquadId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [AK_CT_Squads] ON dbo.CT_Squads
(
	SquadCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE TABLE dbo.CT_Types (
	TypeId BIGINT IDENTITY(1,1) NOT NULL,
	TypeCode NVARCHAR(100) NOT NULL,
	TypeName NVARCHAR(100) NOT NULL,
 CONSTRAINT [PK_CT_Types] PRIMARY KEY CLUSTERED 
(
	TypeId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [AK_CT_Types] ON dbo.CT_Types
(
	TypeCode ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
