//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFirstWCFService")]
    public interface IFirstWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/DoWork", ReplyAction="http://tempuri.org/IFirstWCFService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/DoWork", ReplyAction="http://tempuri.org/IFirstWCFService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/First", ReplyAction="http://tempuri.org/IFirstWCFService/FirstResponse")]
        string First(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/First", ReplyAction="http://tempuri.org/IFirstWCFService/FirstResponse")]
        System.Threading.Tasks.Task<string> FirstAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/Second", ReplyAction="http://tempuri.org/IFirstWCFService/SecondResponse")]
        string Second();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/Second", ReplyAction="http://tempuri.org/IFirstWCFService/SecondResponse")]
        System.Threading.Tasks.Task<string> SecondAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/Third", ReplyAction="http://tempuri.org/IFirstWCFService/ThirdResponse")]
        string Third(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWCFService/Third", ReplyAction="http://tempuri.org/IFirstWCFService/ThirdResponse")]
        System.Threading.Tasks.Task<string> ThirdAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstWCFServiceChannel : ConsApp.ServiceReference1.IFirstWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstWCFServiceClient : System.ServiceModel.ClientBase<ConsApp.ServiceReference1.IFirstWCFService>, ConsApp.ServiceReference1.IFirstWCFService {
        
        public FirstWCFServiceClient() {
        }
        
        public FirstWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string First(string name) {
            return base.Channel.First(name);
        }
        
        public System.Threading.Tasks.Task<string> FirstAsync(string name) {
            return base.Channel.FirstAsync(name);
        }
        
        public string Second() {
            return base.Channel.Second();
        }
        
        public System.Threading.Tasks.Task<string> SecondAsync() {
            return base.Channel.SecondAsync();
        }
        
        public string Third(string name) {
            return base.Channel.Third(name);
        }
        
        public System.Threading.Tasks.Task<string> ThirdAsync(string name) {
            return base.Channel.ThirdAsync(name);
        }
    }
}
